### ISSUE TITLE
2.13.0: Auto-search by URL broken

### ISSUE THREAD

**Issue by manzing** [buttercup/buttercup-browser-extension#322]
Hello

Buttercup was working fine but after latest update, the database is correctly loaded (using webdav on pcloud) but no credentials appear when clicking button next to credentials fields.

Firefox ver 72.0.2 
Windows 10 x64 1903

Am I alone ?

Revert to previous version 2.12 : everything is OK.

Thanks

**Comment by perry-mitchell** [comment]
I’ll check on this shortly.. it was working when I released it. Will try production copy.

**Comment by perry-mitchell** [comment]
Works fine for me..

![image](https://user-images.githubusercontent.com/3869469/72987814-d2ba6680-3df3-11ea-815f-d0aaa5a93610.png)

**Comment by manzing** [comment]
Thanks for checking.
The issue occured at work on my PC.
I just tried at home and have the same issue.
I disabled all other extensions and restart: still the same.
![2020-01-23 18_56_33-Sign in to GitHub · GitHub](https://user-images.githubusercontent.com/2737265/73010335-87fc1700-3e12-11ea-91c2-52d2c220c5f1.png)

Same configuration, W10 x64, Firefox 72.0.2 but i have to mention that i use french version of Firefox on both computers.

Not sure of what you expect for debugging, but I have a bunch of this console error: 

Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 27 background-index.js:1
    createSyncMiddleware moz-extension://1bed277e-893f-486a-bf57-f922252683b0/background-index.js:1

Hope this helps

**Comment by manzing** [comment]
Using 2.12 version of Buttercup extension : 

![2020-01-23 19_36_59-Sign in to GitHub · GitHub](https://user-images.githubusercontent.com/2737265/73013089-e2e43d00-3e17-11ea-8d19-d2bb16a5694b.png)

**Comment by perry-mitchell** [comment]
Ok, confirmed this as a breakdown in the searching functionality in core. By the looks of things it should have failed a long time ago, so I'm not sure why we're only seeing this now. I'll be releasing a patch shortly!

**Comment by perry-mitchell** [comment]
Released in 2.13.1
