### ISSUE TITLE
[owncloud] webdav does not work

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-browser-extension#336]
I haven't found any related issue, I hope I didn't miss one.

### Problem
Every time I try to add a new archive via webDAV (owncloud) I get a red error message (see errors below).

### Scenario

1. Click on the plus Icon to add a archive
2. Select webDAV and type in your credentials
3. Click on "Connect".
4. An error message appears.

### What I tried:

- connect to https://upload.xxxxxx.net/remote.php/dav/files/julian/
- connect to https://upload.xxxxxx.net/remote.php/dav/files/
- connect to https://upload.xxxxxx.net/remote.php/dav/
- connect to https://upload.xxxxxx.net/remote.php/

### System Information
OS: MacOS 10.15.3 (MB 15'' Mid 2014)
Buttercup extension: v2.15.0
Owncloud: 10.4.0.4
Chrome: 80.0.3987.149
Firefox: 74.0 (64-Bit)

### Error messages
@perry-mitchell if you need access to my owncloud in order to reproduce this issue, just send me a message via keybase :)

#### Chrome

> A connection attempt to 'https://upload.xxxxx.net/remote.php/dav/files/julian/' has failed: Cannot read property 'getDirectoryContents' of null

````setup-index.js:85 [info] Creating WebDAV connection to: https://upload.xxxxx.net/remote.php/dav/files/julian/
setup-index.js:85 [info] Testing WebDAV connection...
setup-index.js:85 [error] WebDAV failed to connect: Cannot read property 'getlastmodified' of undefined
setup-index.js:85 [error] Failed establishing WebDAV connection: https://upload.xxxxx.net/remote.php/dav/files/julian/
setup-index.js:85 [info] Fetching remote contents for path: /
setup-buttercup.js:432 TypeError: Cannot read property 'getDirectoryContents' of null
    at fetchRemoteContents (setup-index.js:66)
    at fetchRemoteDirectory (setup-index.js:66)
    at setup-index.js:66
    at setup-index.js:54
    at Object.onReady (setup-vendor.js:1)
    at RemoteExplorer.componentDidMount (setup-index.js:66)
    at setup-buttercup.js:432
    at exports.unstable_runWithPriority (setup-buttercup.js:432)
    at fg (setup-buttercup.js:432)
    at Yj (setup-buttercup.js:432)
Pi @ setup-buttercup.js:432
setup-index.js:54 TypeError: Cannot read property 'getDirectoryContents' of null
    at fetchRemoteContents (setup-index.js:66)
    at fetchRemoteDirectory (setup-index.js:66)
    at setup-index.js:66
    at setup-index.js:54
    at Object.onReady (setup-vendor.js:1)
    at RemoteExplorer.componentDidMount (setup-index.js:66)
    at setup-buttercup.js:432
    at exports.unstable_runWithPriority (setup-buttercup.js:432)
    at fg (setup-buttercup.js:432)
    at Yj (setup-buttercup.js:432)
(anonymous) @ setup-index.js:54
````

#### Firefox
> Failed connecting to 'webdav' resource
A connection attempt to 'https://upload.xxxx.net/remote.php/dav/files/julian/' has failed: Object(...)(...) is null

````
onmozfullscreenchange sollte nicht mehr verwendet werden. setup-buttercup.js:432:677724
onmozfullscreenerror sollte nicht mehr verwendet werden. setup-buttercup.js:432:677724
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src"). setup-buttercup.js:432:2604912
[info] Creating WebDAV connection to: https://upload.xxxxx.net/remote.php/dav/ setup-index.js:85:8211
[info] Testing WebDAV connection... setup-index.js:85:8211
[error] WebDAV failed to connect: t is undefined setup-index.js:85:8211
[error] Failed establishing WebDAV connection: https://upload.xxxxx.net/remote.php/dav/ setup-index.js:85:8211
[info] Fetching remote contents for path: / setup-index.js:85:8211
TypeError: "Object(...)(...) is null"
    fetchRemoteContents moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:66
    fetchRemoteDirectory moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:66
    onReady moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:66
    createThunkMiddleware moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:54
    bindActionCreator moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    componentDidMount moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:66
    Yj moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    unstable_runWithPriority moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    fg moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    Yj moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    Lj moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    ig moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    unstable_runWithPriority moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    fg moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    ig moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    jg moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    Rg moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    enqueueSetState moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    setState moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    onStateChange moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    notify moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    notifyNestedSubs moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    onStateChange moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    dispatch moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    createSyncMiddleware moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:43
    a moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    createThunkMiddleware moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:54
    dispatch moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    onConnectWebDAVBasedSource moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:54
setup-buttercup.js:432:533586
TypeError: "Object(...)(...) is null"
    fetchRemoteContents moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:66
    fetchRemoteDirectory moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:66
    onReady moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:66
    createThunkMiddleware moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:54
    bindActionCreator moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    componentDidMount moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:66
    Yj moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    unstable_runWithPriority moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    fg moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    Yj moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    Lj moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    ig moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    unstable_runWithPriority moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    fg moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    ig moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    jg moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    Rg moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    enqueueSetState moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    setState moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-buttercup.js:432
    onStateChange moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    notify moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    notifyNestedSubs moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    onStateChange moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    dispatch moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    createSyncMiddleware moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:43
    a moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    createThunkMiddleware moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:54
    dispatch moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-vendor.js:1
    onConnectWebDAVBasedSource moz-extension://6a5df914-dd35-6a46-8675-8684d4bb07cc/setup-index.js:54
setup-index.js:54:73884
````

**Comment by perry-mitchell** [comment]
@julianpoemp Messaged on keybase. Thanks!

**Comment by perry-mitchell** [comment]
Thanks again for the help @julianpoemp - I pushed an update, should come out soon. Chrome is a bit slower these days. 2.15.1 has the fix.

**Comment by julianpoemp** [comment]
@perry-mitchell Thank you very much!

**Comment by julianpoemp** [comment]
@perry-mitchell it works with Firefox. I couldn't test it with Chrome, because the version 2.15.1 updated is still not available in the chrome web store... as soon as I can test it and confirm that it's working, I'll close this issue.
![grafik](https://user-images.githubusercontent.com/25926588/78423225-3f0fdc80-7665-11ea-9e32-8ba27dda16b7.png)

**Comment by julianpoemp** [comment]
it works now, thank you very much @perry-mitchell !

**Comment by modzilla99** [comment]
Same issue in chrome 83 on Windows, Firefox does work.

**Comment by Claywd** [comment]
Still having this issue in Chrome for Windows as well. Works in firefox using https://fqdn/remote.php/dav. Not sure what's broken here but issue should be reopened.

**Comment by Claywd** [comment]
EEk. The issue is in edge (built on chromium) not chrome. Chrome is also working.
